project:
  type: website
  output-dir: docs

website:
  title: "Quincy Noel"
  image: QuincyNoel.png
  about:
    template: trestles
    image-shape: rounded
    image-width: 15em
    links:
      - text: LinkedIn
        href: https://www.linkedin.com/in/quincynoel/
      - text: GitHub
        href: https://github.com/quincy-noel
      - text: School Email
        href: mailto:quincy.noel@colostate.edu
      - text: Personal Email
        href: mailto:qcnoel10@gmail.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.html
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
