project:
  type: website
  output-dir: docs
  resources:
      - files/**
      - images/**

website:
  site-url: https://quincy-noel.github.io/
  title: "Quincy Noel"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - morph
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual
